package co.geographs.agrinsa.dao.business;

// default package
// Generated 01-mar-2013 8:02:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MiembrosRolId generated by hbm2java
 */
@Embeddable
public class MiembrosRolId implements java.io.Serializable {

	private int rolId;
	private int usuarioId;

	public MiembrosRolId() {
	}

	public MiembrosRolId(int rolId, int usuarioId) {
		this.rolId = rolId;
		this.usuarioId = usuarioId;
	}

	@Column(name = "rol_id", nullable = false)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "usuario_id", nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MiembrosRolId))
			return false;
		MiembrosRolId castOther = (MiembrosRolId) other;

		return (this.getRolId() == castOther.getRolId())
				&& (this.getUsuarioId() == castOther.getUsuarioId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRolId();
		result = 37 * result + this.getUsuarioId();
		return result;
	}

}
