package co.geographs.agrinsa.dao.business;

// default package
// Generated 01-mar-2013 8:02:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MiembrosRol generated by hbm2java
 */
@Entity
@Table(name = "miembros_rol", schema = "dbo", catalog = "agrinsagdb")
public class MiembrosRol implements java.io.Serializable {

	private MiembrosRolId id;
	private Roles roles;
	private Usuarios usuarios;

	public MiembrosRol() {
	}

	public MiembrosRol(MiembrosRolId id, Roles roles, Usuarios usuarios) {
		this.id = id;
		this.roles = roles;
		this.usuarios = usuarios;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rolId", column = @Column(name = "rol_id", nullable = false)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "usuario_id", nullable = false)) })
	public MiembrosRolId getId() {
		return this.id;
	}

	public void setId(MiembrosRolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_id", nullable = false, insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

}
