package co.geographs.agrinsa.dao.business;

// default package
// Generated 04-mar-2013 20:50:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permisos generated by hbm2java
 */
@Entity
@Table(name = "permisos", schema = "dbo", catalog = "agrinsagdb")
public class Permisos implements java.io.Serializable {

	private int permisoId;
	private String tipo;
	private String opcion;
	private String nombreRecurso;
	private String descripcion;

	public Permisos() {
	}

	public Permisos(int permisoId, String tipo, String opcion,
			String nombreRecurso, String descripcion) {
		this.permisoId = permisoId;
		this.tipo = tipo;
		this.opcion = opcion;
		this.nombreRecurso = nombreRecurso;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "permiso_id", unique = true, nullable = false)
	public int getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(int permisoId) {
		this.permisoId = permisoId;
	}

	@Column(name = "tipo", nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "opcion", nullable = false, length = 50)
	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	@Column(name = "nombre_recurso", nullable = false)
	public String getNombreRecurso() {
		return this.nombreRecurso;
	}

	public void setNombreRecurso(String nombreRecurso) {
		this.nombreRecurso = nombreRecurso;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
