package co.geographs.agrinsa.dao.business;

// default package
// Generated 01-mar-2013 8:02:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermisosRol generated by hbm2java
 */
@Entity
@Table(name = "permisos_rol", schema = "dbo", catalog = "agrinsagdb")
public class PermisosRol implements java.io.Serializable {

	private PermisosRolId id;
	private Roles roles;
	private Permisos permisos;

	public PermisosRol() {
	}

	public PermisosRol(PermisosRolId id, Roles roles, Permisos permisos) {
		this.id = id;
		this.roles = roles;
		this.permisos = permisos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rolId", column = @Column(name = "rol_id", nullable = false)),
			@AttributeOverride(name = "permisoId", column = @Column(name = "permiso_id", nullable = false)) })
	public PermisosRolId getId() {
		return this.id;
	}

	public void setId(PermisosRolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_id", nullable = false, insertable = false, updatable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permiso_id", nullable = false, insertable = false, updatable = false)
	public Permisos getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Permisos permisos) {
		this.permisos = permisos;
	}

}
