package co.geographs.agrinsa.dao.business;

// default package
// Generated 01-mar-2013 8:02:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "dbo", catalog = "agrinsagdb")
public class Roles implements java.io.Serializable {

	private int rolId;
	private String rol;
	private Set<MiembrosRol> miembrosRols = new HashSet(0);
	private Set<PermisosRol> permisosRols = new HashSet(0);

	public Roles() {
	}

	public Roles(int rolId, String rol) {
		this.rolId = rolId;
		this.rol = rol;
	}

	public Roles(int rolId, String rol, Set<MiembrosRol> miembrosRols, Set<PermisosRol> permisosRols) {
		this.rolId = rolId;
		this.rol = rol;
		this.miembrosRols = miembrosRols;
		this.permisosRols = permisosRols;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "rol_id", unique = true, nullable = false)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "rol", nullable = false, length = 50)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<MiembrosRol> getMiembrosRols() {
		return this.miembrosRols;
	}

	public void setMiembrosRols(Set<MiembrosRol> miembrosRols) {
		this.miembrosRols = miembrosRols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<PermisosRol> getPermisosRols() {
		return this.permisosRols;
	}

	public void setPermisosRols(Set<PermisosRol> permisosRols) {
		this.permisosRols = permisosRols;
	}

}
