package co.geographs.agrinsa.dao.business;

// default package
// Generated 01-mar-2013 8:02:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", schema = "dbo", catalog = "agrinsagdb")
public class Usuarios implements java.io.Serializable {

	private int usuarioId;
	private String usuario;
	private String password;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private boolean habilitado;
	private Set<MiembrosRol> miembrosRols = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int usuarioId, String usuario, String password,
			String primerNombre, String primerApellido, boolean habilitado) {
		this.usuarioId = usuarioId;
		this.usuario = usuario;
		this.password = password;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.habilitado = habilitado;
	}

	public Usuarios(int usuarioId, String usuario, String password,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, boolean habilitado, Set miembrosRols) {
		this.usuarioId = usuarioId;
		this.usuario = usuario;
		this.password = password;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.habilitado = habilitado;
		this.miembrosRols = miembrosRols;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "usuario_id", unique = true, nullable = false)
	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "usuario", nullable = false, length = 50,unique = true)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "primer_nombre", nullable = false, length = 50)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 50)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 50)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 50)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "habilitado", nullable = false)
	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<MiembrosRol> getMiembrosRols() {
		return this.miembrosRols;
	}

	public void setMiembrosRols(Set<MiembrosRol> miembrosRols) {
		this.miembrosRols = miembrosRols;
	}

}
